import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css";
import "@/app/styles/buttons.css";
import "@/app/styles/forms.css";
import Providers from "./providers";
import {Navbar} from "@/components/layout/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-6`}
      >
        <Providers>
          <Navbar />
          <div className="w-2/3 mx-auto py-10">{children} </div>
        </Providers>
      </body>
    </html>
  );
}
