export const SHIPMENT_PENDING = "PENDING";
export const SHIPMENT_SHIPPED_FULLY = "SHIPMENT_SHIPPED_FULLY";
export const SHIPMENT_SHIPPED_PARTLY = "SHIPMENT_SHIPPED_PARTLY";

export const SHIPMENT_STATUSES = [
  SHIPMENT_PENDING,
  SHIPMENT_SHIPPED_FULLY,
  SHIPMENT_SHIPPED_PARTLY,
];
