export const SHIPMENT_PENDING = "PENDING";
export const SHIPMENT_SHIPPED = "SHIPPED";
export const SHIPMENT_SHIPPABLE = "SHIPPABLE";

export const SHIPMENT_STATUSES = [SHIPMENT_PENDING, SHIPMENT_SHIPPED, SHIPMENT_SHIPPABLE];
