export const EMPLOYMENT_STATUS_EMPLOYED = "zaposlen";
export const EMPLOYMENT_STATUS_UNEMPLOYED = "nezaposlen";
export const EMPLOYMENT_STATUS_PENDING = "na čekanju";

export const EMPLOYMENT_STATUSES = [
  EMPLOYMENT_STATUS_EMPLOYED,
  EMPLOYMENT_STATUS_UNEMPLOYED,
  EMPLOYMENT_STATUS_PENDING,
];
